var g_resources = [ 
//Picture
	{src: 'images/room.jpg'},
	{src: 'images/guro.png'},
	{src: 'images/guro_2.png'},
	{src: 'images/guro_3.png'},
	{src: 'images/bubble.png'},
	{src: 'images/mainButton1.png'},
	{src: 'images/mainButton2.png'},
	{src: 'images/mainButton1_2.png'},
	{src: 'images/mainButton2_2.png'},
	{src: 'images/logo.png'},
	{src: 'images/note.png'},
	{src: 'images/button.png'},
	{src: 'images/button_2.png'},
	{src: 'images/PC.png'},				
	{src: 'images/PC_2.png'},
	{src: 'images/TV.png'},
	{src: 'images/TV_2.png'},
	{src: 'images/audio.png'},
	{src: 'images/audio_2.png'},
	{src: 'images/certificate.png'},
	{src: 'images/fox.png'},
	{src: 'images/fox_2.png'},
	{src: 'images/gameover.png'},
	{src: 'images/icon1.png'},
	{src: 'images/icon2.png'},
	{src: 'images/icon3.png'},
	{src: 'images/icon4.png'},
	{src: 'images/icon1_2.png'},
	{src: 'images/icon2_2.png'},
	{src: 'images/icon3_2.png'},
	{src: 'images/icon4_2.png'},
	{src: 'images/message.png'},
	{src: 'images/monitor.png'},
	{src: 'images/proframe.png'},
	{src: 'images/screen.png'},

 //effect
    {src: 'sound/theme.mp3'},
    {src: 'sound/menu.mp3'},
    {src: 'sound/gameOver.mp3'}
];
